language: node_js
node_js:
- '10'
deploy:
  api_key:
    secure: uY9geVjaV31Vp78W71YfKRBK7vqItKSAH0BwHcaWF7IpbYOKlM0BuGIt//zSBDRHLriSEFON0N7MQl1p0gUQdK1ku5/qqwl23RgmP2oK1j27ORJuP7G+XWIizk6BKna8a/XwGe2fzh+BRIxIXVZGXVmclpxyJb5MA/dkXOj0nSboM6GEcSooU3j/qiKiIi6kybPeq3aiv0O2W/fCse1rzw+6fOs2ELUIyKSJ2R4d7XiwzhRuu554gLgCJklgQ1WhNzVkzi2r5XqQTUhejvTFX6z6723zBcljRHux35mkhhGZ6yLUsB5g9tBu1Q3otms0HiGVHfl83k5ZxPmwsmPFHq/Qklq/Pjb9Rx8mwSfkbciUyY8apGKRITCkPoEcDRx1kv9AZ2EDuXvtTyGZteV4axvwdn9lQtO+BKENGr+4LdrmdTWnYOqRlKhIYWcMQr0lXFGJOaKIIpzVYpbRF1NEOcTGLQxfEASbcAzOUBr1VnQQnaKLNix/VzWG1vFPJKGFbwJuV9xScZdOAih6CkDOG6BM9r6K54xridHOVAeLPu/4nAY99B62G53rNK9qWzde0BhbuPY95944saA+cXLyyBMB5N7j8A4RVV50HDcQ2+kDp0uk5S5H7EcbZUAwJG3YCmgdrfb9KrE5hLQa5b60NrvP2ThtlFUhaZirQ0DaX/4=
  email: julian@dotcore.co.il
  provider: npm
  skip_cleanup: true
  on:
    tags: true
script:
- npm test
