language: node_js
node_js:
- '8'
deploy:
  api_key:
    secure: qyKGxHPdmCfqT2OHHEwpIAVUXAJmWGZdmkiYucwjLpoeq5CfUAy27Lm+3UORpUuXcAC2p9k8K0q8E36ZZiT5FPDm/Lnp3ExZkFasMSNcR7SIB+340xfa1mpx6Qs8wzKsFiy7iBetPO9J+qVwJ5VAZz1rP9cOUJx+3c9RomaEPA7Su5g/35lApJVahZAkQHGHi13/Wagidf11cw/RK31zbjxVAzdJlWgX92Fwxvu4P/pLENR0xHPnwwVjneVuRgxiIzcxtzhIvvlleKhGpyJXjK37iemOZvCMJHI7yo3svKysswSXS04Ofq1ggq8DK8p3qeEQeWDp9+JoIFvkL1mH3fJoVid9XUtueGj4ZfnaB+WEMqSgQNbY70t6u/bkgsrBOVYMU/TsHBewE0MFe2w4nrFT90q42yrLj6vQ89EwrCDdD3hGm9vOlKdd3Mt+3WYZaPaDCOiVtUiG+2MCQIBr4IB3SzbWKvudm6tpBk7pnF/ILmJNXixxTXzLEYgDYlfaEohkdWY3egVeC5nMRZlsLttS7AxAge9srbIbDhFsET7+v90p9n28WcFdGcbXc9MYHzvVtsdGGpta8XIzoYKHVzgltKCFTYL8Ub0SwDizCY5B8NaNDKHVHjvhufWgsFYMDaIljXtVjLTp8lPhsKW7x1gze0nQz78PfanJb7NIBw4=
  email: julian@dotcore.co.il
  provider: npm
  on:
    tags: true
script:
- npm test
